language: php

php:
    - 7.2
    - 7.3
    - 7.4

services:
    - mysql

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update
    - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot
    - mysql -uroot --password= test < tests/test.sql

install:
    - travis_retry composer install --no-interaction --prefer-dist

script: phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover